### ISSUE TITLE
Failing tests on Ubuntu using python-msgpack v0.3

### ISSUE THREAD

**Issue by jollyroger** [nicolasff/webdis#92]
Nicolas, I've found that webdis fails msgpack-related tests using python-mspack with version 0.3.0. All tests pass with python-msgpack version 0.2.0 installed. However this package only is available in Debian and not Ubuntu. This affects recent Ubuntu versions(saucy and upcoming trusty), here is detailed output:

<pre>
python tests/basic.py
............F..FF.....
======================================================================
FAIL: test_error (__main__.TestMsgPack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/basic.py", line 145, in wrapper
    fn(self)
  File "tests/basic.py", line 192, in test_error
    self.assertTrue(isinstance(obj['UNKNOWN'], tuple))
AssertionError: False is not true

======================================================================
FAIL: test_list (__main__.TestMsgPack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/basic.py", line 145, in wrapper
    fn(self)
  File "tests/basic.py", line 183, in test_list
    self.assertTrue(obj == {'LRANGE': ('abc', 'def')})
AssertionError: False is not true

======================================================================
FAIL: test_set (__main__.TestMsgPack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/basic.py", line 145, in wrapper
    fn(self)
  File "tests/basic.py", line 157, in test_set
    self.assertTrue(obj == {'SET': (True, 'OK')})
AssertionError: False is not true

----------------------------------------------------------------------
Ran 22 tests in 0.053s

FAILED (failures=3)</pre>

These errors do not appear for Debian jessie(current testing) and sid(unstable). Debian has two packages related to python and msgpack that are used in the test suite: `python-msgpack` with version 0.3.0 of the library and `msgpack-python` with version 0.2.0 of the same library. Ubuntu has just `msgpack-python` package that points to the 0.3.0 version. I assume version 0.2.0 will be dropped soon from Debian as well.

**Comment by jollyroger** [comment]
Friendly bump. Do you want me to send Pull Request that fixes the tests?

**Comment by nicolasff** [comment]
A pull request would be much appreciated!

**Comment by jollyroger** [comment]
@nicolasff  I've created pull request for this issue (and some others) as you requested. Hope they are fine.
